CREATE USER atharva;

GRANT ALL PRIVILEGES ON DATABASE auth_service TO atharva;

CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY,
username VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(50) NOT NULL,
role VARCHAR(20) NOT NULL DEFAULT 'user'
);